---
output: 
  pdf_document:
    keep_tex: yes
    fig_caption: yes
    number_sections: yes
geometry: margin=2.54cm
title: "Central Appalachian Mine Closures"
subtitle: "https://github.com/hgs13/EDA_Final_Project_2020"
author: "Hannah Smith"
fontsize: 12pt
mainfont: Times New Roman

---

\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()

# Load your packages
library(tidyverse)
library(viridis)
library(rvest)
library(ggrepel)
library(shiny)
library(shinythemes)
library(viridis)
library(RColorBrewer)
library(colormap)
library(harrypotter)

# Set your ggplot theme
mytheme <- theme_classic() +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top")
theme_set(mytheme)

# Load your datasets
harlan <- read.csv("./Data/Raw/EIA_MineData_Harlan_Raw.csv")

dickenson <- read.csv("./Data/Raw/EIA_MineData_Dickenson_Raw.csv")

```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 
```{r, include = FALSE}
harlan$year <- as.numeric(harlan$year)
harlan$ARC <- as.logical(harlan$ARC)
harlan$mine.status <- as.character(harlan$mine.status)
harlan$operation.type <- as.character(harlan$operation.type)
harlan$production.stons <- as.numeric(harlan$production.stons)
harlan$average.employees <- as.numeric(harlan$average.employees)


dickenson$year <- as.numeric(dickenson$year)
dickenson$ARC <- as.logical(dickenson$ARC)
class(dickenson$mine.name)
```

```{r}
library(RColorBrewer)
nb.cols <- 31
mycolors <- colorRampPalette(brewer.pal(31, "Set2"))(nb.cols)

hppal <- hp(n = 31, house = "Hufflepuff")
```

```{r}
harlan.wrangled <- filter(harlan, production.stons > 1, mine.status == "Active", 
                          operation.type == "Mine only", average.employees < 20 
                          | average.employees > 100)
harlan.plot <- ggplot(harlan.wrangled, aes(x = year, y = average.employees, color = mine.name)) +
  geom_line() +
  labs(x = "Year", y = "Number of Employees", color = "Mine") +
  xlim(2001, 2011) +
  scale_fill_manual(values=hppal)
  
  #scale_color_viridis(discrete = TRUE, option = "magma")
  #theme(legend.position = "none")
print(harlan.plot)
```

\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 

